ball = self._lblball
rnd = System.Random
lpdl = self._lblleft
rpdl = self._lblright
ball.Top += self.ballup
ball.Left += 8 * self.balld
rscore = int(self._rightscore.Text)
lscore = int(self._leftscore.Text)
tball = self.timerball
tdum = self._timerdummy
tbool = self._timerboolean
tmult = self._timermulti
tleft = self._timerleft
tright  = self._timerright
bl = self._lblball
lblf = self._lblleft
lbrt = self._lblright
num1 = rnd.Next(55, 600)
lpdl.Top = ball.Top - num1